-- Backup existing booking_preferences data
CREATE TABLE IF NOT EXISTS booking_preferences_backup AS
SELECT * FROM booking_preferences;

-- Drop the current booking_preferences table
DROP TABLE IF EXISTS booking_preferences;

-- Create a new booking_preferences table with updated columns
CREATE TABLE booking_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_name TEXT NOT NULL,
    preferred_days TEXT NOT NULL, -- Stored as JSON string
    preferred_times TEXT NOT NULL, -- Stored as JSON string
    rec_account_email TEXT NOT NULL,
    rec_account_password TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    playtime_duration INTEGER DEFAULT 60, -- New column
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create index for efficient queries
CREATE INDEX booking_preferences_created_at_idx ON booking_preferences (created_at DESC);

-- Restore data from backup, setting default playtime_duration to 60
INSERT INTO booking_preferences (
    court_name, 
    preferred_days, 
    preferred_times, 
    rec_account_email, 
    rec_account_password, 
    phone_number, 
    created_at
)
SELECT 
    court_name, 
    preferred_days, 
    preferred_times, 
    rec_account_email, 
    rec_account_password, 
    phone_number, 
    created_at
FROM booking_preferences_backup;

-- Optionally, drop the backup table when safe
-- DROP TABLE booking_preferences_backup;

-- Grant appropriate permissions
ALTER TABLE booking_preferences ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access for authenticated users" 
ON booking_preferences
FOR SELECT 
USING (true);

-- Allow all operations for authenticated users
CREATE POLICY "Allow all operations for authenticated users" 
ON booking_preferences
USING (true); 